import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'storage.dart';
import 'pdf_exporter.dart';

void main() => runApp(const NibrasDocsApp());

class DocItem {
  final String id;
  String title, content, category, tags;
  bool favorite, pinned, deleted;
  DateTime created, modified;
  DocItem({required this.id, required this.title, this.content='', this.category='Personal', this.tags='', this.favorite=false, this.pinned=false, this.deleted=false, DateTime? created, DateTime? modified})
      : created=created ?? DateTime.now(), modified=modified ?? DateTime.now();
  Map<String,dynamic> toJson()=>{'id':id,'title':title,'content':content,'category':category,'tags':tags,'favorite':favorite,'pinned':pinned,'deleted':deleted,'created':created.toIso8601String(),'modified':modified.toIso8601String()};
  factory DocItem.fromJson(Map<String,dynamic> j)=>DocItem(id:j['id'],title:j['title'],content:j['content']??'',category:j['category']??'Personal',tags:j['tags']??'',favorite:j['favorite']??false,pinned:j['pinned']??false,deleted:j['deleted']??false,created:DateTime.tryParse(j['created']??''),modified:DateTime.tryParse(j['modified']??''));
}

class NibrasDocsApp extends StatefulWidget { const NibrasDocsApp({super.key}); @override State<NibrasDocsApp> createState()=>_AppState(); }
class _AppState extends State<NibrasDocsApp>{ bool dark=true; void toggle()=>setState(()=>dark=!dark);
  @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Nibras Docs',themeMode:dark?ThemeMode.dark:ThemeMode.light,
    darkTheme:_theme(Brightness.dark),theme:_theme(Brightness.light),home:Splash(onTheme:toggle));
  ThemeData _theme(Brightness b){final dark=b==Brightness.dark; return ThemeData(brightness:b,useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff14c9ff),brightness:b),scaffoldBackgroundColor:dark?const Color(0xff061226):const Color(0xfff3f7ff),fontFamily:'sans-serif',cardTheme:CardThemeData(color:dark?const Color(0xff0d203d):Colors.white,elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22))));}
}

class Splash extends StatefulWidget {final VoidCallback onTheme; const Splash({super.key,required this.onTheme}); @override State<Splash> createState()=>_SplashState();}
class _SplashState extends State<Splash>{ @override void initState(){super.initState(); Future.delayed(const Duration(milliseconds:1500),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Home(onTheme:widget.onTheme)));});}
 @override Widget build(BuildContext c)=>Scaffold(body:Container(decoration:const BoxDecoration(gradient:RadialGradient(center:Alignment.topRight,radius:1.3,colors:[Color(0xff123c7a),Color(0xff061226),Color(0xff020816)])),child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Image.asset('assets/images/nibras_icon.png',width:150,height:150),const SizedBox(height:18),const Text('Nibras Docs',style:TextStyle(fontSize:38,fontWeight:FontWeight.w800)),const Text('CREATE  •  EDIT  •  ORGANIZE',style:TextStyle(color:Color(0xff6addff),letterSpacing:2)),const SizedBox(height:38),const CircularProgressIndicator(),const SizedBox(height:18),const Text('Preparing your workspace...',style:TextStyle(color:Colors.white60))]))));}

class Home extends StatefulWidget {final VoidCallback onTheme; const Home({super.key,required this.onTheme}); @override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{ final docs=<DocItem>[]; final folders=<String>['Hamısı','Personal','Work','Study','Archive']; final store=LocalStore(); int tab=0; String q=''; String activeFolder='Hamısı'; bool loaded=false;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{final data=await store.load();docs.addAll(((data['documents']??[]) as List).map((e)=>DocItem.fromJson(Map<String,dynamic>.from(e))));for(final f in ((data['folders']??[]) as List)){final name=f.toString();if(name.isNotEmpty&&!folders.contains(name))folders.add(name);}if(mounted)setState(()=>loaded=true);}
 Future<void> _save()async{await store.save({'documents':docs.map((e)=>e.toJson()).toList(),'folders':folders.where((f)=>f!='Hamısı').toList()});if(mounted)setState((){});}
 List<DocItem> get shown{var x=docs.where((d)=>tab==2?d.deleted:!d.deleted).where((d)=>tab!=1||d.favorite).where((d)=>activeFolder=='Hamısı'||d.category==activeFolder).where((d)=>d.title.toLowerCase().contains(q.toLowerCase())||d.content.toLowerCase().contains(q.toLowerCase())||d.tags.toLowerCase().contains(q.toLowerCase())).toList();x.sort((a,b){if(a.pinned!=b.pinned)return a.pinned?-1:1;return b.modified.compareTo(a.modified);});return x;}
 Future<void> edit([DocItem? d])async{final item=d??DocItem(id:DateTime.now().microsecondsSinceEpoch.toString(),title:'Yeni sənəd',category:activeFolder=='Hamısı'?'Personal':activeFolder);await Navigator.push(context,MaterialPageRoute(builder:(_)=>Editor(doc:item,folders:folders.where((f)=>f!='Hamısı').toList(),onSave:(x){if(d==null)docs.add(x);_save();})));}
 @override Widget build(BuildContext c){if(!loaded)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(title:Row(children:[Image.asset('assets/images/nibras_icon.png',width:40,height:40),const SizedBox(width:10),const Text('Nibras Docs',style:TextStyle(fontWeight:FontWeight.w800))]),actions:[IconButton(tooltip:'Backup yarat',onPressed:()async{final f=await store.backup({'documents':docs.map((e)=>e.toJson()).toList()});if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Backup yaradıldı: ${f.path}')));}},icon:const Icon(Icons.backup_outlined)),IconButton(onPressed:widget.onTheme,icon:const Icon(Icons.contrast)),PopupMenuButton(itemBuilder:(_)=>[const PopupMenuItem(value:'about',child:Text('Nibras Code haqqında'))],onSelected:(_)=>showAboutDialog(context:context,applicationName:'Nibras Docs',applicationVersion:'1.0.0'))]),
 body:Column(children:[_dashboard(),_folderBar(),Padding(padding:const EdgeInsets.fromLTRB(16,8,16,12),child:TextField(onChanged:(v)=>setState(()=>q=v),decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'Sənədlərdə axtar...',filled:true,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none)))),
 Expanded(child:shown.isEmpty?_empty():ListView.builder(padding:const EdgeInsets.fromLTRB(16,0,16,100),itemCount:shown.length,itemBuilder:(_,i)=>_card(shown[i])))]),
 floatingActionButton:tab==2?null:FloatingActionButton.extended(onPressed:()=>edit(),icon:const Icon(Icons.add),label:const Text('Yeni sənəd')),
 bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Ana səhifə'),NavigationDestination(icon:Icon(Icons.star_outline),selectedIcon:Icon(Icons.star),label:'Seçilmişlər'),NavigationDestination(icon:Icon(Icons.delete_outline),selectedIcon:Icon(Icons.delete),label:'Səbət')]));}

 Future<void> _newFolder()async{final c=TextEditingController();final name=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('Yeni qovluq'),content:TextField(controller:c,autofocus:true,decoration:const InputDecoration(hintText:'Qovluq adı')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Ləğv et')),FilledButton(onPressed:()=>Navigator.pop(context,c.text.trim()),child:const Text('Yarat'))]));if(name!=null&&name.isNotEmpty&&!folders.contains(name)){folders.add(name);activeFolder=name;await _save();}}
 Future<void> _manageFolder(String old)async{final action=await showModalBottomSheet<String>(context:context,builder:(_)=>SafeArea(child:Wrap(children:[ListTile(leading:const Icon(Icons.drive_file_rename_outline),title:const Text('Adını dəyiş'),onTap:()=>Navigator.pop(context,'rename')),ListTile(leading:const Icon(Icons.delete_outline),title:const Text('Qovluğu sil'),subtitle:const Text('Sənədlər Personal qovluğuna köçürüləcək'),onTap:()=>Navigator.pop(context,'delete'))])));if(action=='rename'){final c=TextEditingController(text:old);final name=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('Qovluğun adını dəyiş'),content:TextField(controller:c,autofocus:true),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Ləğv et')),FilledButton(onPressed:()=>Navigator.pop(context,c.text.trim()),child:const Text('Saxla'))]));if(name!=null&&name.isNotEmpty&&!folders.contains(name)){for(final d in docs.where((d)=>d.category==old)){d.category=name;}folders[folders.indexOf(old)]=name;if(activeFolder==old)activeFolder=name;await _save();}}else if(action=='delete'){for(final d in docs.where((d)=>d.category==old)){d.category='Personal';}folders.remove(old);if(activeFolder==old)activeFolder='Hamısı';await _save();}}
 Widget _folderBar()=>SizedBox(height:54,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:12),children:[...folders.map((f)=>Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:GestureDetector(onLongPress:f=='Hamısı'?null:()=>_manageFolder(f),child:ChoiceChip(label:Text(f),selected:activeFolder==f,onSelected:(_)=>setState(()=>activeFolder=f))))),Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:ActionChip(avatar:const Icon(Icons.create_new_folder_outlined,size:18),label:const Text('Qovluq'),onPressed:_newFolder))]));
  Widget _dashboard()=>SizedBox(height:92,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:12),children:[_stat('Sənəd',docs.where((d)=>!d.deleted).length,Icons.description),_stat('Seçilmiş',docs.where((d)=>d.favorite&&!d.deleted).length,Icons.star),_stat('Pin',docs.where((d)=>d.pinned&&!d.deleted).length,Icons.push_pin),_stat('Səbət',docs.where((d)=>d.deleted).length,Icons.delete)]));
 Widget _stat(String label,int count,IconData icon)=>Container(width:120,margin:const EdgeInsets.all(6),padding:const EdgeInsets.all(12),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xff11366c),Color(0xff0b203f)]),borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0xff1dcfff).withValues(alpha:.25))),child:Row(children:[Icon(icon,color:const Color(0xff37d7ff)),const SizedBox(width:8),Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$count',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Text(label,style:const TextStyle(fontSize:11,color:Colors.white70))])])));

 Widget _empty()=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.description_outlined,size:72,color:Color(0xff22cfff)),const SizedBox(height:14),Text(tab==1?'Seçilmiş sənəd yoxdur':'İlk sənədini yarat',style:const TextStyle(fontSize:21,fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('Sadə, sürətli və oflayn iş sahəsi') ]));
 Widget _card(DocItem d)=>Card(child:ListTile(contentPadding:const EdgeInsets.all(14),leading:Container(width:52,height:52,decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xff176cff),Color(0xff1de1ff)]),borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.description,color:Colors.white)),title:Row(children:[if(d.pinned)const Padding(padding:EdgeInsets.only(right:6),child:Icon(Icons.push_pin,size:16)),Expanded(child:Text(d.title,style:const TextStyle(fontWeight:FontWeight.w700)))]),subtitle:Text('${d.category} • ${d.content.trim().isEmpty?0:d.content.trim().split(RegExp(r"\\s+")).length} söz${d.tags.trim().isEmpty?'':' • ${d.tags}'}'),onTap:()=>edit(d),trailing:PopupMenuButton<String>(onSelected:(v)async{if(v=='fav')d.favorite=!d.favorite;if(v=='pin')d.pinned=!d.pinned;if(v=='pdf')await exportPdf(d);if(v=='epub'&&mounted)await Navigator.push(context,MaterialPageRoute(builder:(_)=>EpubPreviewScreen(doc:d)));if(v=='share')await exportDoc(d);if(v=='delete')d.deleted=true;if(v=='restore')d.deleted=false;if(v=='forever')docs.remove(d);_save();},itemBuilder:(_)=>[PopupMenuItem(value:'fav',child:Text(d.favorite?'Seçilmişdən çıxar':'Seçilmiş et')),PopupMenuItem(value:'pin',child:Text(d.pinned?'Sancağı çıxar':'Yuxarı sancaqla')),const PopupMenuItem(value:'pdf',child:Text('PDF ixrac et')),const PopupMenuItem(value:'epub',child:Text('EPUB önizləmə')),const PopupMenuItem(value:'share',child:Text('TXT paylaş')),if(!d.deleted)const PopupMenuItem(value:'delete',child:Text('Səbətə at')) else ...[const PopupMenuItem(value:'restore',child:Text('Bərpa et')),const PopupMenuItem(value:'forever',child:Text('Həmişəlik sil'))]])));
 Future<void> exportPdf(DocItem d)async{final o=await Navigator.push<Map<String,dynamic>>(context,MaterialPageRoute(builder:(_)=>const PdfOptionsScreen()));if(o==null)return;final file=await PdfExporter.create(title:d.title,content:d.content,category:d.category,tags:d.tags,family:o['font'],pageSize:o['size'],landscape:o['landscape']);await Share.shareXFiles([XFile(file.path)],text:'Nibras Docs PDF');}
 Future<void> exportDoc(DocItem d)async{final dir=await getTemporaryDirectory();final safe=d.title.replaceAll(RegExp(r'[^a-zA-Z0-9_-]'),'_');final f=File('${dir.path}/$safe.txt');await f.writeAsString('${d.title}\n\n${d.content}');await Share.shareXFiles([XFile(f.path)],text:'Nibras Docs');}
}

class Editor extends StatefulWidget{final DocItem doc;final List<String> folders;final ValueChanged<DocItem> onSave;const Editor({super.key,required this.doc,required this.folders,required this.onSave});@override State<Editor> createState()=>_EditorState();}
class _EditorState extends State<Editor>{late final TextEditingController title,body,tags;String category='Personal';
 @override void initState(){super.initState();title=TextEditingController(text:widget.doc.title);body=TextEditingController(text:widget.doc.content);tags=TextEditingController(text:widget.doc.tags);category=widget.doc.category;}
 void save(){widget.doc.title=title.text.trim().isEmpty?'Adsız sənəd':title.text.trim();widget.doc.content=body.text;widget.doc.tags=tags.text.trim();widget.doc.category=category;widget.doc.modified=DateTime.now();widget.onSave(widget.doc);Navigator.pop(context);}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Sənəd redaktoru'),actions:[IconButton(onPressed:save,icon:const Icon(Icons.check_circle))]),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:title,style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold),decoration:const InputDecoration(hintText:'Başlıq',border:InputBorder.none)),Row(children:[const Text('Kateqoriya: '),DropdownButton<String>(value:widget.folders.contains(category)?category:widget.folders.first,items:widget.folders.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>category=v!)),const Spacer(),ValueListenableBuilder(valueListenable:body,builder:(_,TextEditingValue v,__)=>Text('${v.text.trim().isEmpty?0:v.text.trim().split(RegExp(r"\\s+")).length} söz'))]),TextField(controller:tags,decoration:const InputDecoration(prefixIcon:Icon(Icons.tag),hintText:'Etiketlər: iş, vacib, layihə')),const Divider(),Expanded(child:TextField(controller:body,maxLines:null,expands:true,textAlignVertical:TextAlignVertical.top,decoration:const InputDecoration(hintText:'Yazmağa başla...',border:InputBorder.none)))])),floatingActionButton:tab==2?null:FloatingActionButton.extended(onPressed:save,icon:const Icon(Icons.save),label:const Text('Saxla')));
}

class PdfOptionsScreen extends StatefulWidget{const PdfOptionsScreen({super.key});@override State<PdfOptionsScreen> createState()=>_PdfOptionsState();}
class _PdfOptionsState extends State<PdfOptionsScreen>{String font='Sans',size='A4';bool landscape=false;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('PDF ixrac ayarları')),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Səhifə ölçüsü',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Wrap(spacing:8,children:['A3','A4','A5','A6','Letter','Legal'].map((x)=>ChoiceChip(label:Text(x),selected:size==x,onSelected:(_)=>setState(()=>size=x))).toList()),const SizedBox(height:20),const Text('Şrift',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Wrap(spacing:8,children:['Sans','Serif','Mono'].map((x)=>ChoiceChip(label:Text(x),selected:font==x,onSelected:(_)=>setState(()=>font=x))).toList()),SwitchListTile(value:landscape,onChanged:(v)=>setState(()=>landscape=v),title:const Text('Landşaft')),FilledButton.icon(onPressed:()=>Navigator.pop(c,{'font':font,'size':size,'landscape':landscape}),icon:const Icon(Icons.picture_as_pdf),label:const Text('PDF yarat'))]));}
class EpubPreviewScreen extends StatefulWidget{final DocItem doc;const EpubPreviewScreen({super.key,required this.doc});@override State<EpubPreviewScreen> createState()=>_EpubPreviewState();}
class _EpubPreviewState extends State<EpubPreviewScreen>{double fs=17;String mode='Sepia',device='Phone';@override Widget build(BuildContext c){final dark=mode=='Dark'||mode=='AMOLED';final bg=mode=='Sepia'?const Color(0xfffff3d2):(dark?Colors.black:Colors.white);final fg=dark?Colors.white:const Color(0xff392f24);final w=device=='Tablet'?520.0:device=='Kindle'?430.0:350.0;return Scaffold(appBar:AppBar(title:const Text('Nibras Docs • EPUB önizləmə')),body:Column(children:[Wrap(spacing:6,children:[...['Phone','Tablet','Kindle'].map((x)=>ChoiceChip(label:Text(x),selected:device==x,onSelected:(_)=>setState(()=>device=x))),...['Light','Sepia','Dark','AMOLED'].map((x)=>ChoiceChip(label:Text(x),selected:mode==x,onSelected:(_)=>setState(()=>mode=x)))]),Expanded(child:Center(child:Container(width:w,margin:const EdgeInsets.all(12),padding:const EdgeInsets.all(28),decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(18),boxShadow:const [BoxShadow(blurRadius:22,color:Colors.black38)]),child:SingleChildScrollView(child:DefaultTextStyle(style:TextStyle(color:fg,fontSize:fs,height:1.55,fontFamily:'serif'),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.doc.title,style:TextStyle(fontSize:fs+10,fontWeight:FontWeight.bold)),const Divider(),Text(widget.doc.content.isEmpty?'Sənədə mətn əlavə edin.':widget.doc.content)])))))),Row(mainAxisAlignment:MainAxisAlignment.center,children:[IconButton(onPressed:()=>setState(()=>fs=(fs-1).clamp(12,28)),icon:const Icon(Icons.text_decrease)),Text('${fs.toInt()}'),IconButton(onPressed:()=>setState(()=>fs=(fs+1).clamp(12,28)),icon:const Icon(Icons.text_increase))]) ]));}}
